# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Python_Prj\SIMIT\SFQ_IbCtrl\currentSupply\subWin_infoOfConnection.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_infoOfConnection(object):
    def setupUi(self, infoOfConnection):
        infoOfConnection.setObjectName("infoOfConnection")
        infoOfConnection.resize(438, 130)
        self.label = QtWidgets.QLabel(infoOfConnection)
        self.label.setGeometry(QtCore.QRect(130, 45, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(infoOfConnection)
        self.label_2.setGeometry(QtCore.QRect(230, 45, 76, 26))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(infoOfConnection)
        QtCore.QMetaObject.connectSlotsByName(infoOfConnection)

    def retranslateUi(self, infoOfConnection):
        _translate = QtCore.QCoreApplication.translate
        infoOfConnection.setWindowTitle(_translate("infoOfConnection", "Information of connection"))
        self.label.setText(_translate("infoOfConnection", "Com Num:"))
