# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Python_Prj\SIMIT\SFQ_IbCtrl\currentSupply\win.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1165, 978)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(520, 35, 140, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(710, 34, 196, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(990, 20, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1040, 34, 84, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(80, 100, 165, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(80, 170, 165, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(80, 240, 165, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(80, 310, 165, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(80, 380, 165, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(80, 450, 165, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(80, 520, 165, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(80, 590, 165, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(80, 660, 165, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(80, 730, 165, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 35, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 35, 165, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 35, 129, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 95, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 165, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 235, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 305, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 375, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(140, 445, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(140, 515, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(140, 585, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(140, 655, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(140, 725, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(300, 95, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setSuffix("")
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMaximum(1000.0)
        self.doubleSpinBox.setProperty("value", 0.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(300, 165, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMaximum(1000.0)
        self.doubleSpinBox_2.setProperty("value", 0.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(300, 235, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_3.setFont(font)
        self.doubleSpinBox_3.setDecimals(3)
        self.doubleSpinBox_3.setMaximum(1000.0)
        self.doubleSpinBox_3.setProperty("value", 0.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(300, 305, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_4.setFont(font)
        self.doubleSpinBox_4.setDecimals(3)
        self.doubleSpinBox_4.setMaximum(1000.0)
        self.doubleSpinBox_4.setProperty("value", 0.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(300, 375, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_5.setFont(font)
        self.doubleSpinBox_5.setDecimals(3)
        self.doubleSpinBox_5.setMaximum(1000.0)
        self.doubleSpinBox_5.setProperty("value", 0.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(300, 445, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_6.setFont(font)
        self.doubleSpinBox_6.setDecimals(3)
        self.doubleSpinBox_6.setMaximum(1000.0)
        self.doubleSpinBox_6.setProperty("value", 0.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(300, 515, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_7.setFont(font)
        self.doubleSpinBox_7.setDecimals(3)
        self.doubleSpinBox_7.setMaximum(1000.0)
        self.doubleSpinBox_7.setProperty("value", 0.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(300, 585, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_8.setFont(font)
        self.doubleSpinBox_8.setDecimals(3)
        self.doubleSpinBox_8.setMaximum(1000.0)
        self.doubleSpinBox_8.setProperty("value", 0.0)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_9.setGeometry(QtCore.QRect(300, 655, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_9.setFont(font)
        self.doubleSpinBox_9.setDecimals(3)
        self.doubleSpinBox_9.setMaximum(1000.0)
        self.doubleSpinBox_9.setProperty("value", 0.0)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_10.setGeometry(QtCore.QRect(300, 725, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.doubleSpinBox_10.setFont(font)
        self.doubleSpinBox_10.setDecimals(3)
        self.doubleSpinBox_10.setMaximum(1000.0)
        self.doubleSpinBox_10.setProperty("value", 0.0)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(500, 95, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser.setFont(font)
        self.textBrowser.setAcceptDrops(True)
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setOpenExternalLinks(False)
        self.textBrowser.setOpenLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_11.setGeometry(QtCore.QRect(710, 95, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_11.setFont(font)
        self.textBrowser_11.setAcceptDrops(True)
        self.textBrowser_11.setAutoFillBackground(False)
        self.textBrowser_11.setOpenExternalLinks(False)
        self.textBrowser_11.setOpenLinks(True)
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(915, 95, 31, 31))
        self.radioButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton.setStyleSheet("QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:         rgb(152,152,152);\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"   \n"
"    background-color: rgb(240,240,240);\n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(950, 95, 31, 31))
        self.radioButton_2.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border:                 2px solid white;\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"    border:                 1px solid gray;\n"
"}\n"
"")
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(910, 90, 76, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_21 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_21.setGeometry(QtCore.QRect(1065, 90, 31, 36))
        self.radioButton_21.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(255, 0, 0);\n"
"    border:                 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"}\n"
"")
        self.radioButton_21.setText("")
        self.radioButton_21.setCheckable(True)
        self.radioButton_21.setObjectName("radioButton_21")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(500, 165, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setAcceptDrops(True)
        self.textBrowser_2.setAutoFillBackground(False)
        self.textBrowser_2.setOpenExternalLinks(False)
        self.textBrowser_2.setOpenLinks(True)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(500, 235, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setAcceptDrops(True)
        self.textBrowser_3.setAutoFillBackground(False)
        self.textBrowser_3.setOpenExternalLinks(False)
        self.textBrowser_3.setOpenLinks(True)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(500, 305, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setAcceptDrops(True)
        self.textBrowser_4.setAutoFillBackground(False)
        self.textBrowser_4.setOpenExternalLinks(False)
        self.textBrowser_4.setOpenLinks(True)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(500, 375, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setAcceptDrops(True)
        self.textBrowser_5.setAutoFillBackground(False)
        self.textBrowser_5.setOpenExternalLinks(False)
        self.textBrowser_5.setOpenLinks(True)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(500, 445, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_6.setFont(font)
        self.textBrowser_6.setAcceptDrops(True)
        self.textBrowser_6.setAutoFillBackground(False)
        self.textBrowser_6.setOpenExternalLinks(False)
        self.textBrowser_6.setOpenLinks(True)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(500, 515, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_7.setFont(font)
        self.textBrowser_7.setAcceptDrops(True)
        self.textBrowser_7.setAutoFillBackground(False)
        self.textBrowser_7.setOpenExternalLinks(False)
        self.textBrowser_7.setOpenLinks(True)
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(500, 585, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_8.setFont(font)
        self.textBrowser_8.setAcceptDrops(True)
        self.textBrowser_8.setAutoFillBackground(False)
        self.textBrowser_8.setOpenExternalLinks(False)
        self.textBrowser_8.setOpenLinks(True)
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_9.setGeometry(QtCore.QRect(500, 655, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_9.setFont(font)
        self.textBrowser_9.setAcceptDrops(True)
        self.textBrowser_9.setAutoFillBackground(False)
        self.textBrowser_9.setOpenExternalLinks(False)
        self.textBrowser_9.setOpenLinks(True)
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_10.setGeometry(QtCore.QRect(500, 725, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_10.setFont(font)
        self.textBrowser_10.setAcceptDrops(True)
        self.textBrowser_10.setAutoFillBackground(False)
        self.textBrowser_10.setOpenExternalLinks(False)
        self.textBrowser_10.setOpenLinks(True)
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_12.setGeometry(QtCore.QRect(710, 165, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_12.setFont(font)
        self.textBrowser_12.setAcceptDrops(True)
        self.textBrowser_12.setAutoFillBackground(False)
        self.textBrowser_12.setOpenExternalLinks(False)
        self.textBrowser_12.setOpenLinks(True)
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_13.setGeometry(QtCore.QRect(710, 235, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_13.setFont(font)
        self.textBrowser_13.setAcceptDrops(True)
        self.textBrowser_13.setAutoFillBackground(False)
        self.textBrowser_13.setOpenExternalLinks(False)
        self.textBrowser_13.setOpenLinks(True)
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_14.setGeometry(QtCore.QRect(710, 305, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_14.setFont(font)
        self.textBrowser_14.setAcceptDrops(True)
        self.textBrowser_14.setAutoFillBackground(False)
        self.textBrowser_14.setOpenExternalLinks(False)
        self.textBrowser_14.setOpenLinks(True)
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_15.setGeometry(QtCore.QRect(710, 375, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_15.setFont(font)
        self.textBrowser_15.setAcceptDrops(True)
        self.textBrowser_15.setAutoFillBackground(False)
        self.textBrowser_15.setOpenExternalLinks(False)
        self.textBrowser_15.setOpenLinks(True)
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_16.setGeometry(QtCore.QRect(710, 445, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_16.setFont(font)
        self.textBrowser_16.setAcceptDrops(True)
        self.textBrowser_16.setAutoFillBackground(False)
        self.textBrowser_16.setOpenExternalLinks(False)
        self.textBrowser_16.setOpenLinks(True)
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_17.setGeometry(QtCore.QRect(710, 515, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_17.setFont(font)
        self.textBrowser_17.setAcceptDrops(True)
        self.textBrowser_17.setAutoFillBackground(False)
        self.textBrowser_17.setOpenExternalLinks(False)
        self.textBrowser_17.setOpenLinks(True)
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.textBrowser_18 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_18.setGeometry(QtCore.QRect(710, 585, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_18.setFont(font)
        self.textBrowser_18.setAcceptDrops(True)
        self.textBrowser_18.setAutoFillBackground(False)
        self.textBrowser_18.setOpenExternalLinks(False)
        self.textBrowser_18.setOpenLinks(True)
        self.textBrowser_18.setObjectName("textBrowser_18")
        self.textBrowser_19 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_19.setGeometry(QtCore.QRect(710, 655, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_19.setFont(font)
        self.textBrowser_19.setAcceptDrops(True)
        self.textBrowser_19.setAutoFillBackground(False)
        self.textBrowser_19.setOpenExternalLinks(False)
        self.textBrowser_19.setOpenLinks(True)
        self.textBrowser_19.setObjectName("textBrowser_19")
        self.textBrowser_20 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_20.setGeometry(QtCore.QRect(710, 725, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.textBrowser_20.setFont(font)
        self.textBrowser_20.setAcceptDrops(True)
        self.textBrowser_20.setAutoFillBackground(False)
        self.textBrowser_20.setOpenExternalLinks(False)
        self.textBrowser_20.setOpenLinks(True)
        self.textBrowser_20.setObjectName("textBrowser_20")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(915, 165, 31, 31))
        self.radioButton_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_3.setStyleSheet("QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:         rgb(152,152,152);\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"   \n"
"    background-color: rgb(240,240,240);\n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(910, 160, 76, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(950, 165, 31, 31))
        self.radioButton_4.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border:                 2px solid white;\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"    border:                 1px solid gray;\n"
"}\n"
"")
        self.radioButton_4.setText("")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(950, 235, 31, 31))
        self.radioButton_6.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border:                 2px solid white;\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"    border:                 1px solid gray;\n"
"}\n"
"")
        self.radioButton_6.setText("")
        self.radioButton_6.setObjectName("radioButton_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(910, 230, 76, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(915, 235, 31, 31))
        self.radioButton_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_5.setStyleSheet("QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:         rgb(152,152,152);\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"   \n"
"    background-color: rgb(240,240,240);\n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.radioButton_5.setText("")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(915, 305, 31, 31))
        self.radioButton_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_7.setStyleSheet("QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:         rgb(152,152,152);\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"   \n"
"    background-color: rgb(240,240,240);\n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.radioButton_7.setText("")
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(950, 305, 31, 31))
        self.radioButton_8.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border:                 2px solid white;\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"    border:                 1px solid gray;\n"
"}\n"
"")
        self.radioButton_8.setText("")
        self.radioButton_8.setObjectName("radioButton_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(910, 300, 76, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(910, 370, 76, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton_10 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_10.setGeometry(QtCore.QRect(950, 375, 31, 31))
        self.radioButton_10.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border:                 2px solid white;\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"    border:                 1px solid gray;\n"
"}\n"
"")
        self.radioButton_10.setText("")
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_9 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_9.setGeometry(QtCore.QRect(915, 375, 31, 31))
        self.radioButton_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_9.setStyleSheet("QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:         rgb(152,152,152);\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"   \n"
"    background-color: rgb(240,240,240);\n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.radioButton_9.setText("")
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_12 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_12.setGeometry(QtCore.QRect(950, 445, 31, 31))
        self.radioButton_12.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border:                 2px solid white;\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"    border:                 1px solid gray;\n"
"}\n"
"")
        self.radioButton_12.setText("")
        self.radioButton_12.setObjectName("radioButton_12")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(910, 440, 76, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.radioButton_11 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_11.setGeometry(QtCore.QRect(915, 445, 31, 31))
        self.radioButton_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_11.setStyleSheet("QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:         rgb(152,152,152);\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"   \n"
"    background-color: rgb(240,240,240);\n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.radioButton_11.setText("")
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_14 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_14.setGeometry(QtCore.QRect(950, 515, 31, 31))
        self.radioButton_14.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border:                 2px solid white;\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"    border:                 1px solid gray;\n"
"}\n"
"")
        self.radioButton_14.setText("")
        self.radioButton_14.setObjectName("radioButton_14")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(910, 510, 76, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.radioButton_13 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_13.setGeometry(QtCore.QRect(915, 515, 31, 31))
        self.radioButton_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_13.setStyleSheet("QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:         rgb(152,152,152);\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"   \n"
"    background-color: rgb(240,240,240);\n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.radioButton_13.setText("")
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_16 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_16.setGeometry(QtCore.QRect(950, 585, 31, 31))
        self.radioButton_16.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border:                 2px solid white;\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"    border:                 1px solid gray;\n"
"}\n"
"")
        self.radioButton_16.setText("")
        self.radioButton_16.setObjectName("radioButton_16")
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(910, 580, 76, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.radioButton_15 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_15.setGeometry(QtCore.QRect(915, 585, 31, 31))
        self.radioButton_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_15.setStyleSheet("QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:         rgb(152,152,152);\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"   \n"
"    background-color: rgb(240,240,240);\n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.radioButton_15.setText("")
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_18 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_18.setGeometry(QtCore.QRect(950, 655, 31, 31))
        self.radioButton_18.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border:                 2px solid white;\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"    border:                 1px solid gray;\n"
"}\n"
"")
        self.radioButton_18.setText("")
        self.radioButton_18.setObjectName("radioButton_18")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(910, 650, 76, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.radioButton_17 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_17.setGeometry(QtCore.QRect(915, 655, 31, 31))
        self.radioButton_17.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_17.setStyleSheet("QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:         rgb(152,152,152);\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"   \n"
"    background-color: rgb(240,240,240);\n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.radioButton_17.setText("")
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_20 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_20.setGeometry(QtCore.QRect(950, 725, 31, 31))
        self.radioButton_20.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border:                 2px solid white;\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"    border:                 1px solid gray;\n"
"}\n"
"")
        self.radioButton_20.setText("")
        self.radioButton_20.setObjectName("radioButton_20")
        self.radioButton_19 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_19.setGeometry(QtCore.QRect(915, 725, 31, 31))
        self.radioButton_19.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_19.setStyleSheet("QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:         rgb(152,152,152);\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"   \n"
"    background-color: rgb(240,240,240);\n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.radioButton_19.setText("")
        self.radioButton_19.setObjectName("radioButton_19")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_10.setGeometry(QtCore.QRect(910, 720, 76, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.radioButton_22 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_22.setGeometry(QtCore.QRect(1065, 160, 31, 36))
        self.radioButton_22.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(255, 0, 0);\n"
"    border:                 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"}\n"
"")
        self.radioButton_22.setText("")
        self.radioButton_22.setObjectName("radioButton_22")
        self.radioButton_23 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_23.setGeometry(QtCore.QRect(1065, 230, 31, 36))
        self.radioButton_23.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(255, 0, 0);\n"
"    border:                 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"}\n"
"")
        self.radioButton_23.setText("")
        self.radioButton_23.setObjectName("radioButton_23")
        self.radioButton_24 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_24.setGeometry(QtCore.QRect(1065, 300, 31, 36))
        self.radioButton_24.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(255, 0, 0);\n"
"    border:                 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"}\n"
"")
        self.radioButton_24.setText("")
        self.radioButton_24.setObjectName("radioButton_24")
        self.radioButton_25 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_25.setGeometry(QtCore.QRect(1065, 370, 31, 36))
        self.radioButton_25.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(255, 0, 0);\n"
"    border:                 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"}\n"
"")
        self.radioButton_25.setText("")
        self.radioButton_25.setObjectName("radioButton_25")
        self.radioButton_26 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_26.setGeometry(QtCore.QRect(1065, 440, 31, 36))
        self.radioButton_26.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(255, 0, 0);\n"
"    border:                 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"}\n"
"")
        self.radioButton_26.setText("")
        self.radioButton_26.setObjectName("radioButton_26")
        self.radioButton_27 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_27.setGeometry(QtCore.QRect(1065, 510, 31, 36))
        self.radioButton_27.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(255, 0, 0);\n"
"    border:                 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"}\n"
"")
        self.radioButton_27.setText("")
        self.radioButton_27.setObjectName("radioButton_27")
        self.radioButton_28 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_28.setGeometry(QtCore.QRect(1065, 580, 31, 36))
        self.radioButton_28.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(255, 0, 0);\n"
"    border:                 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"}\n"
"")
        self.radioButton_28.setText("")
        self.radioButton_28.setObjectName("radioButton_28")
        self.radioButton_29 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_29.setGeometry(QtCore.QRect(1065, 650, 31, 36))
        self.radioButton_29.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(255, 0, 0);\n"
"    border:                 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"}\n"
"")
        self.radioButton_29.setText("")
        self.radioButton_29.setObjectName("radioButton_29")
        self.radioButton_30 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_30.setGeometry(QtCore.QRect(1065, 720, 31, 36))
        self.radioButton_30.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgb(255, 0, 0);\n"
"    border:                 2px solid white;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"}\n"
"")
        self.radioButton_30.setText("")
        self.radioButton_30.setObjectName("radioButton_30")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(870, 20, 41, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_18.setFont(font)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.radioButton_31 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_31.setGeometry(QtCore.QRect(915, 30, 31, 31))
        self.radioButton_31.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_31.setStyleSheet("QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color:         rgb(152,152,152);\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"   \n"
"    background-color: rgb(240,240,240);\n"
"    border: 1px solid gray;\n"
"}\n"
"")
        self.radioButton_31.setText("")
        self.radioButton_31.setObjectName("radioButton_31")
        self.radioButton_32 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_32.setGeometry(QtCore.QRect(950, 30, 31, 31))
        self.radioButton_32.setStyleSheet("\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  25px;\n"
"    height:                 25px;\n"
"    border-radius:          13px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border:                 2px solid white;\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:       rgb(240, 240, 240);\n"
"    border:                 1px solid gray;\n"
"}\n"
"")
        self.radioButton_32.setText("")
        self.radioButton_32.setObjectName("radioButton_32")
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(910, 25, 76, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(485, 790, 197, 140))
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.groupBox_11.raise_()
        self.groupBox_10.raise_()
        self.groupBox_9.raise_()
        self.groupBox_8.raise_()
        self.groupBox_7.raise_()
        self.groupBox_6.raise_()
        self.groupBox_3.raise_()
        self.groupBox_2.raise_()
        self.radioButton_4.raise_()
        self.groupBox_4.raise_()
        self.groupBox.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit_8.raise_()
        self.lineEdit_9.raise_()
        self.lineEdit_10.raise_()
        self.doubleSpinBox.raise_()
        self.doubleSpinBox_2.raise_()
        self.doubleSpinBox_3.raise_()
        self.doubleSpinBox_4.raise_()
        self.doubleSpinBox_5.raise_()
        self.doubleSpinBox_6.raise_()
        self.doubleSpinBox_7.raise_()
        self.doubleSpinBox_8.raise_()
        self.doubleSpinBox_9.raise_()
        self.doubleSpinBox_10.raise_()
        self.textBrowser.raise_()
        self.textBrowser_11.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.radioButton_21.raise_()
        self.textBrowser_2.raise_()
        self.textBrowser_3.raise_()
        self.textBrowser_4.raise_()
        self.textBrowser_5.raise_()
        self.textBrowser_6.raise_()
        self.textBrowser_7.raise_()
        self.textBrowser_8.raise_()
        self.textBrowser_9.raise_()
        self.textBrowser_10.raise_()
        self.textBrowser_12.raise_()
        self.textBrowser_13.raise_()
        self.textBrowser_14.raise_()
        self.textBrowser_15.raise_()
        self.textBrowser_16.raise_()
        self.textBrowser_17.raise_()
        self.textBrowser_18.raise_()
        self.textBrowser_19.raise_()
        self.textBrowser_20.raise_()
        self.radioButton_3.raise_()
        self.radioButton_6.raise_()
        self.radioButton_5.raise_()
        self.radioButton_7.raise_()
        self.radioButton_8.raise_()
        self.groupBox_5.raise_()
        self.radioButton_10.raise_()
        self.radioButton_9.raise_()
        self.radioButton_12.raise_()
        self.radioButton_11.raise_()
        self.radioButton_14.raise_()
        self.radioButton_13.raise_()
        self.radioButton_16.raise_()
        self.radioButton_15.raise_()
        self.radioButton_18.raise_()
        self.radioButton_17.raise_()
        self.radioButton_20.raise_()
        self.radioButton_19.raise_()
        self.radioButton_22.raise_()
        self.radioButton_23.raise_()
        self.radioButton_24.raise_()
        self.radioButton_25.raise_()
        self.radioButton_26.raise_()
        self.radioButton_27.raise_()
        self.radioButton_28.raise_()
        self.radioButton_29.raise_()
        self.radioButton_30.raise_()
        self.label_18.raise_()
        self.radioButton_31.raise_()
        self.radioButton_32.raise_()
        self.label_19.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1165, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_entered_param_into_an_init_file = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("f:\\Python_Prj\\SIMIT\\SFQ_IbCtrl\\currentSupply\\icons/writeToAFile.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_entered_param_into_an_init_file.setIcon(icon)
        self.actionSave_entered_param_into_an_init_file.setObjectName("actionSave_entered_param_into_an_init_file")
        self.actionLoad_param_into_GUI_from_the_init_file = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("f:\\Python_Prj\\SIMIT\\SFQ_IbCtrl\\currentSupply\\icons/loadParam.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_param_into_GUI_from_the_init_file.setIcon(icon1)
        self.actionLoad_param_into_GUI_from_the_init_file.setObjectName("actionLoad_param_into_GUI_from_the_init_file")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("f:\\Python_Prj\\SIMIT\\SFQ_IbCtrl\\currentSupply\\icons/Help.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDocumentation.setIcon(icon2)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionProduct_web_site = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("f:\\Python_Prj\\SIMIT\\SFQ_IbCtrl\\currentSupply\\icons/device.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProduct_web_site.setIcon(icon3)
        self.actionProduct_web_site.setObjectName("actionProduct_web_site")
        self.menuFile.addAction(self.actionSave_entered_param_into_an_init_file)
        self.menuFile.addAction(self.actionLoad_param_into_GUI_from_the_init_file)
        self.menuFile.addSeparator()
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionProduct_web_site)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LDC/E-multicurrent10     @Author: Mengfei Zhao"))
        self.label_4.setText(_translate("MainWindow", "Voltage"))
        self.label_5.setText(_translate("MainWindow", "Photodiode"))
        self.label_6.setText(_translate("MainWindow", "All On"))
        self.label_7.setText(_translate("MainWindow", "Status"))
        self.label_8.setText(_translate("MainWindow", "#1"))
        self.label_9.setText(_translate("MainWindow", "#2"))
        self.label_10.setText(_translate("MainWindow", "#3"))
        self.label_11.setText(_translate("MainWindow", "#4"))
        self.label_12.setText(_translate("MainWindow", "#5"))
        self.label_13.setText(_translate("MainWindow", "#6"))
        self.label_14.setText(_translate("MainWindow", "#7"))
        self.label_15.setText(_translate("MainWindow", "#8"))
        self.label_16.setText(_translate("MainWindow", "#9"))
        self.label_17.setText(_translate("MainWindow", "#10"))
        self.label_3.setText(_translate("MainWindow", "SetCurrent"))
        self.label.setText(_translate("MainWindow", "Channel"))
        self.label_2.setText(_translate("MainWindow", "Alias"))
        self.label_18.setText(_translate("MainWindow", "All Off"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave_entered_param_into_an_init_file.setText(_translate("MainWindow", "Save_entered_param_into_an_init_file"))
        self.actionLoad_param_into_GUI_from_the_init_file.setText(_translate("MainWindow", "Load_param_into_GUI_from_the_init_file"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionProduct_web_site.setText(_translate("MainWindow", "Product web site"))
import icons_rc
